import Head from 'next/head'
import Image from 'next/image'
import SearchBar from '../components/searchBar'
import MoviesTableView from '../components/moviesTableView'

export default function Home({query, setQuery}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 pt-8 bg-yellow">
        <SearchBar query={query} setQuery={setQuery} />
        <MoviesTableView query={query} />
      </main>
    </div>
  );
}
