import Head from 'next/head'
import Image from 'next/image'
import SearchBar from '../components/searchBar'
import MoviesTableView from '../components/moviesTableView'
import styles from '../styles/Home.module.css'

export default function Home({query, setQuery}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SearchBar query={query} setQuery={setQuery} />
        <MoviesTableView query={query} />
      </main>
    </div>
  );
}
